[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[lint]
exclude_lints = [
    "mixed-case-variable",
    "screaming-snake-case-immutable",
    "unwrapped-modifier-logic" ,
    "unsafe-typecast" ,
    "screaming-snake-case-const"
]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

    [fuzz]
    show_logs = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
